fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'https://github.com/Pintta'
description 'https://github.com/Pintta/Broken-npc'
version '1.0.0'
client_script 'pintta.lua'
file 'popcycle.dat'
data_file 'POPSCHED_FILE' 'popcycle.dat'
